# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit, push]
repos:
- repo: https://github.com/sqlfluff/sqlfluff
  rev: 0.10.1
  hooks:
    - id: sqlfluff-lint
      additional_dependencies: ['.[dbt]']
    