name: '{{ cookiecutter.project_slug }}'
version: '1.0.0'
config-version: 2

profile: '{{ cookiecutter.project_slug }}'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  {{ cookiecutter.project_slug }}:
    # Config indicated by + and applies to all files under models/example/
    +materialized: view
